name: trnews
description: "A Turkish news application"
publish_to: 'none'
version: 2.0.9+15

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  flutter_html: ^3.0.0
  url_launcher: ^6.1.14
  share_plus: ^11.0.0
  flutter_gen_runner: ^5.4.0
  carousel_slider: ^5.0.0
  flutter_slidable: ^4.0.0
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.0.0
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  flutter_bloc: ^8.1.3
  # Routing
  auto_route: ^7.8.4
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2 
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cross_connectivity: ^3.3.0
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Localization

  # Notifications
  flutter_local_notifications: ^19.1.0
  firebase_messaging: ^15.2.7
  firebase_core: ^3.13.0
  # Utils
  equatable: ^2.0.5
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  jwt_decoder: ^2.0.1
  collection: ^1.19.0
  


  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/


  fonts:
    - family: Roobert PRO
      fonts:
        - asset: assets/fonts/RoobertPRO-Light.ttf
          weight: 300
        - asset: assets/fonts/RoobertPRO-Regular.ttf
          weight: 400
        - asset: assets/fonts/RoobertPRO-Medium.ttf
          weight: 500
        - asset: assets/fonts/RoobertPRO-Bold.ttf
          weight: 700

        
        


flutter_gen:
  assets:
    enabled: true
  integrations:
    flutter_svg: true


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/Icon-App.png"
